steps:
  # Build the backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mindfulai-backend', '.']
    dir: 'backend'

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push'
    args: ['push', 'gcr.io/$PROJECT_ID/mindfulai-backend']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'mindfulai-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/mindfulai-backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8000'
      - '--memory'
      - '1Gi'

images:
  - 'gcr.io/$PROJECT_ID/mindfulai-backend'

options:
  logging: CLOUD_LOGGING_ONLY
